
package artifact;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Statistics", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Statistics {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "numTwitter", targetNamespace = "http://ws/", className = "artifact.NumTwitter")
    @ResponseWrapper(localName = "numTwitterResponse", targetNamespace = "http://ws/", className = "artifact.NumTwitterResponse")
    public int numTwitter();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emailsDigest", targetNamespace = "http://ws/", className = "artifact.EmailsDigest")
    @ResponseWrapper(localName = "emailsDigestResponse", targetNamespace = "http://ws/", className = "artifact.EmailsDigestResponse")
    public int emailsDigest();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "totalNews", targetNamespace = "http://ws/", className = "artifact.TotalNews")
    @ResponseWrapper(localName = "totalNewsResponse", targetNamespace = "http://ws/", className = "artifact.TotalNewsResponse")
    public int totalNews();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "totalNewsByGenre", targetNamespace = "http://ws/", className = "artifact.TotalNewsByGenre")
    @ResponseWrapper(localName = "totalNewsByGenreResponse", targetNamespace = "http://ws/", className = "artifact.TotalNewsByGenreResponse")
    public String totalNewsByGenre();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emailsNonDigest", targetNamespace = "http://ws/", className = "artifact.EmailsNonDigest")
    @ResponseWrapper(localName = "emailsNonDigestResponse", targetNamespace = "http://ws/", className = "artifact.EmailsNonDigestResponse")
    public int emailsNonDigest();

}
