
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatisticsService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8081/Statistics?wsdl")
public class StatisticsService
    extends Service
{

    private final static URL STATISTICSSERVICE_WSDL_LOCATION;
    private final static WebServiceException STATISTICSSERVICE_EXCEPTION;
    private final static QName STATISTICSSERVICE_QNAME = new QName("http://ws/", "StatisticsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/Statistics?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATISTICSSERVICE_WSDL_LOCATION = url;
        STATISTICSSERVICE_EXCEPTION = e;
    }

    public StatisticsService() {
        super(__getWsdlLocation(), STATISTICSSERVICE_QNAME);
    }

    public StatisticsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATISTICSSERVICE_QNAME, features);
    }

    public StatisticsService(URL wsdlLocation) {
        super(wsdlLocation, STATISTICSSERVICE_QNAME);
    }

    public StatisticsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATISTICSSERVICE_QNAME, features);
    }

    public StatisticsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatisticsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Statistics
     */
    @WebEndpoint(name = "StatisticsPort")
    public Statistics getStatisticsPort() {
        return super.getPort(new QName("http://ws/", "StatisticsPort"), Statistics.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Statistics
     */
    @WebEndpoint(name = "StatisticsPort")
    public Statistics getStatisticsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "StatisticsPort"), Statistics.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATISTICSSERVICE_EXCEPTION!= null) {
            throw STATISTICSSERVICE_EXCEPTION;
        }
        return STATISTICSSERVICE_WSDL_LOCATION;
    }

}
